CREATE SCHEMA `payroll_schema` ;







CREATE TABLE payrollservice_schema.payroll (
	emp_type VARCHAR(10) NOT NULL,tax_name VARCHAR(30) NULL,tax_per DOUBLE NULL,tax_type VARCHAR(20)
NULL);
INSERT INTO payrollservice_schema.payroll
(emp_type,tax_name,tax_per,tax_type)
VALUES
("FULLTIME","INCOME TAX",10.0,"DEDUCTION"),
("FULLTIME","PROFESSIONAL TAX",2.0,"DEDUCTION"),
("FULLTIME","PROFESSIONAL TAX",2.0,"DEDUCTION"),
("FULLTIME","PROVIDENT FUND",12.0,"DEDUCTION"),
("FULLTIME","ESI",0.75,"DEDUCTION"),
("FULLTIME","HEALTH INSURANCE",1.5,"DEDUCTION"),
("FULLTIME","PENSION CONTRIBUTION",5.0,"DEDUCTION"),
("FULLTIME","HRA",20.0,"ALLOWANCE"),
("FULLTIME","INTERNET ALLOWANCE",2.0,"ALLOWANCE"),
("PARTTIME","INCOME TAX",5.0,"DEDUCTION"),
("PARTTIME","PROFESSIONAL TAX",1.0,"DEDUCTION"),
("PARTTIME","INTERNET ALLOWANCE",2.0,"ALLOWANCE");


CREATE TABLE `payrollservice_schema`.`employee_allowances` (
  `emp_id` VARCHAR(10) NOT NULL,
  `allowance_name` VARCHAR(45) NULL,
  `amount` DOUBLE NULL);
  